### ISSUE TITLE
Deploy manifest is still referencing previous version

### ISSUE THREAD

**Issue by albundy83** [outscale-dev/cloud-provider-osc#151]
Hello,

maybe in the deploy manifest file you should update also the version to point to the current release `v0.1.0` ?

Here the line that could be updated:
https://github.com/outscale-dev/cloud-provider-osc/blob/35e2165ed80b2c2e06c036dea1d84cdf93f3492f/deploy/osc-ccm-manifest.yml#L143

and changed to:
```yaml
          image: outscale/cloud-provider-osc:v0.1.0
```

/kind bug

**Comment by outscale-mdr** [comment]
Hello @albundy83,

Thank you for pointing that out. We will update that in the next release.

**Comment by outscale-mdr** [comment]
This file has not been updated after the migration towards Outscale API therefore in the manifest, you will have to add these two variables:
- [OSC_SECRET_KEY](https://github.com/outscale-dev/cloud-provider-osc/blob/35e2165ed80b2c2e06c036dea1d84cdf93f3492f/deploy/k8s-osc-ccm/templates/osc-ccm.yaml#L198)
- [OSC_ACCESS_KEY](https://github.com/outscale-dev/cloud-provider-osc/blob/35e2165ed80b2c2e06c036dea1d84cdf93f3492f/deploy/k8s-osc-ccm/templates/osc-ccm.yaml#L204)

We have found a way to synchronize autmatically the helm chart and this file so that it does not happen again.

Thank you !
